print("Hello, World!")
print("Hello World")
print("Learning Git properly")
print("Third practice")
print("Hello World")
print("Practice from Git Bash")
print("Learning step by step")

print("final steps")
print ("this is second day working")
print("Updated successfully")
print("Completed")
